# Generated by Django 4.2.4 on 2023-11-06 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testemunho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['id'], 'verbose_name': 'comentário', 'verbose_name_plural': 'comentários'},
        ),
        migrations.AlterModelOptions(
            name='testemunho',
            options={'ordering': ['id'], 'verbose_name': 'testemunho', 'verbose_name_plural': 'testemunhos'},
        ),
        migrations.RenameField(
            model_name='testemunho',
            old_name='comentariosAtivo',
            new_name='comentarios_ativo',
        ),
        migrations.RenameField(
            model_name='testemunho',
            old_name='dataCriacao',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='comentario',
            name='comentario_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testemunho.comentario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='conteudo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='testemunho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='testemunho.testemunho'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='testemunho.usuario'),
        ),
        migrations.AlterField(
            model_name='testemunho',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testemunhos', to='testemunho.usuario'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testemunho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testemunho.testemunho')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testemunho.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'testemunho')},
            },
        ),
    ]
